### ISSUE TITLE
Increasing memory usage over time leading to crash

### ISSUE THREAD

**Issue by esille** [sp-hash/TeamBlackMiner#112]
Hi,

I have noticed that memory usage of TBMiner process increases over time, usually ends as process crash and miner restart. 

OS: HiveOS (Latest 0.6-211@211107)
Miner version: Latest (1.23)

Relevant example logs:

> 2021-11-08T06:36:01+01:00	[107367.329625][   T98] [TTM] Failed allocating swap storage
> 
> 2021-11-08T07:31:06+01:00	[110673.175797][   T98] Node 0 hugepages_total=128 hugepages_free=128 hugepages_surp=0 hugepages_size=2048kB
> 2021-11-08T07:31:06+01:00	[110673.175796][   T98] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
> 2021-11-08T06:36:01+01:00	[107367.329675][ T2572] Node 0 hugepages_total=128 hugepages_free=128 hugepages_surp=0 hugepages_size=2048kB
> 2021-11-08T06:36:01+01:00	[107367.329674][ T2572] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
> 2021-11-08T07:31:06+01:00	[110673.175806][   T98] 0 pages hwpoisoned
> 2021-11-08T07:31:06+01:00	[110673.175805][   T98] 0 pages cma reserved
> 2021-11-08T07:31:06+01:00	[110673.175805][   T98] 60098 pages reserved
> 2021-11-08T07:31:06+01:00	[110673.175805][   T98] 0 pages HighMem/MovableOnly
> 2021-11-08T07:31:06+01:00	[110673.175804][   T98] 2076206 pages RAM
> 2021-11-08T07:31:06+01:00	[110673.175804][   T98] Total swap = 8388604kB
> 2021-11-08T07:31:06+01:00	[110673.175804][   T98] Free swap  = 5148808kB
> 2021-11-08T07:31:06+01:00	[110673.175803][   T98] Swap cache stats: add 995920, delete 937211, find 10145744/10159512
> 2021-11-08T07:31:06+01:00	[110673.175802][   T98] 58736 pages in swap cache
> 2021-11-08T07:31:06+01:00	[110673.175797][   T98] 179032 total pagecache pages
> 2021-11-08T07:31:06+01:00	[110673.175792][   T98] Node 0 Normal: 1*4kB (U) 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 1*512kB (U) 0*1024kB 0*2048kB 0*4096kB = 516kB
> 2021-11-08T07:31:06+01:00	[110673.175789][   T98] Node 0 DMA32: 0*4kB 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 0kB
> 2021-11-08T07:31:06+01:00	[110673.175781][   T98] Node 0 DMA: 0*4kB 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 0kB
> 2021-11-08T07:31:06+01:00	[110673.175780][   T98] lowmem_reserve[]: 0 0 0 0 0
> 2021-11-08T07:31:06+01:00	[110673.175775][   T98] Node 0 Normal free:1028kB min:181292kB low:195236kB high:209180kB active_anon:4441676kB inactive_anon:1125020kB active_file:68836kB inactive_file:36364kB unevictable:132kB writepending:0kB present:6799360kB managed:6624588kB mlocked:0kB kernel_stack:4464kB pagetables:24128kB bounce:0kB free_pcp:4052kB local_pcp:456kB free_cma:0kB
> 2021-11-08T07:31:06+01:00	[110673.175770][   T98] lowmem_reserve[]: 0 0 6464 6464 6464
> 2021-11-08T07:31:06+01:00	[110673.175764][   T98] Node 0 DMA32 free:500kB min:13708kB low:16620kB high:19532kB active_anon:1386564kB inactive_anon:36792kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:1489480kB managed:1423944kB mlocked:0kB kernel_stack:0kB pagetables:4kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
> 2021-11-08T07:31:06+01:00	[110673.175757][   T98] lowmem_reserve[]: 0 1351 7815 7815 7815
> 2021-11-08T07:31:06+01:00	[110673.175752][   T98] Node 0 DMA free:12kB min:132kB low:164kB high:196kB active_anon:0kB inactive_anon:15828kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15984kB managed:15900kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
> 2021-11-08T07:31:06+01:00	[110673.175750][   T98] Node 0 active_anon:5828056kB inactive_anon:1178824kB active_file:68836kB inactive_file:35980kB unevictable:132kB isolated(anon):0kB isolated(file):0kB mapped:52548kB dirty:0kB writeback:0kB shmem:376164kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 4651008kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
> 2021-11-08T07:31:06+01:00	[110673.175747][   T98]  free:257 free_pcp:951 free_cma:0
> 2021-11-08T07:31:06+01:00	[110673.175747][   T98]  mapped:13137 shmem:94041 pagetables:6033 bounce:0
> 2021-11-08T07:31:06+01:00	[110673.175747][   T98]  slab_reclaimable:6513 slab_unreclaimable:12444
> 2021-11-08T07:31:06+01:00	[110673.175747][   T98]  unevictable:33 dirty:0 writeback:0 unstable:0
> 2021-11-08T07:31:06+01:00	[110673.175747][   T98]  active_file:17209 inactive_file:8995 isolated_file:0
> 2021-11-08T07:31:06+01:00	[110673.175747][   T98] active_anon:1457014 inactive_anon:294706 isolated_anon:0
> 2021-11-08T07:31:06+01:00	[110673.175743][   T98] Mem-Info:
> 2021-11-08T07:31:06+01:00	[110673.175733][   T98]  ret_from_fork+0x1f/0x40
> 2021-11-08T07:31:06+01:00	[110673.175732][   T98]  ? kthread_park+0x90/0x90
> 2021-11-08T07:31:06+01:00	[110673.175731][   T98]  kthread+0x113/0x130
> 2021-11-08T07:31:06+01:00	[110673.175730][   T98]  ? balance_pgdat+0x560/0x560
> 2021-11-08T07:31:06+01:00	[110673.175729][   T98]  ? wait_woken+0x80/0x80
> 2021-11-08T07:31:06+01:00	[110673.175727][   T98]  kswapd+0x14c/0x3d0
> 2021-11-08T07:31:06+01:00	[110673.175725][   T98]  balance_pgdat+0x255/0x560
> 2021-11-08T07:31:06+01:00	[110673.175723][   T98]  shrink_node+0xcc/0x420
> 2021-11-08T07:31:06+01:00	[110673.175722][   T98]  shrink_slab+0x22f/0x2b0
> 2021-11-08T07:31:06+01:00	[110673.175721][   T98]  do_shrink_slab+0x122/0x2c0
> 2021-11-08T07:31:06+01:00	[110673.175719][   T98]  ttm_tt_shrinker_scan+0x40/0x70 [amdttm]
> 2021-11-08T07:31:06+01:00	[110673.175717][   T98]  amdttm_bo_swapout+0x204/0x350 [amdttm]
> 2021-11-08T07:31:06+01:00	[110673.175715][   T98]  ttm_tt_swapout+0x121/0x1c0 [amdttm]
> 2021-11-08T07:31:06+01:00	[110673.175709][   T98]  ? set_page_dirty+0xe/0xb0
> 2021-11-08T07:31:06+01:00	[110673.175705][   T98]  shmem_read_mapping_page_gfp+0x42/0x80
> 2021-11-08T07:31:06+01:00	[110673.175704][   T98]  shmem_getpage_gfp+0x16f/0x8c0
> 2021-11-08T07:31:06+01:00	[110673.175702][   T98]  shmem_alloc_and_acct_page+0x72/0x1b0
> 2021-11-08T07:31:06+01:00	[110673.175700][   T98]  shmem_alloc_page+0x47/0x90
> 2021-11-08T07:31:06+01:00	[110673.175697][   T98]  alloc_pages_vma+0x7c/0x210
> 2021-11-08T07:31:06+01:00	[110673.175696][   T98]  __alloc_pages_nodemask+0x2cf/0x320
> 2021-11-08T07:31:06+01:00	[110673.175695][   T98]  ? ___slab_alloc+0x207/0x5f0
> 2021-11-08T07:31:06+01:00	[110673.175694][   T98]  __alloc_pages_slowpath+0xd06/0xd40
> 2021-11-08T07:31:06+01:00	[110673.175693][   T98]  ? wake_all_kswapds+0x54/0xb0
> 2021-11-08T07:31:06+01:00	[110673.175691][   T98]  warn_alloc+0xfe/0x160
> 2021-11-08T07:31:06+01:00	[110673.175689][   T98]  dump_stack+0x66/0x81
> 2021-11-08T07:31:06+01:00	[110673.175681][   T98] Call Trace:
> 2021-11-08T07:31:06+01:00	[110673.175680][   T98] Hardware name: Default string Default string/SKYBAY, BIOS 5.12 12/05/2017
> 2021-11-08T07:31:06+01:00	[110673.175680][   T98] CPU: 2 PID: 98 Comm: kswapd0 Tainted: G           OE     5.4.0-hiveos #140.hiveos.210813
> 2021-11-08T07:31:06+01:00	[110673.175675][   T98] kswapd0: page allocation failure: order:0, mode:0xc40(GFP_NOFS), nodemask=(null),cpuset=/,mems_allowed=0
> 2021-11-08T07:31:06+01:00	[110673.175673][   T98] warn_alloc: 116 callbacks suppressed
> 2021-11-08T06:36:01+01:00	[107367.710213][   T98]   node 0: slabs: 142, objs: 2924, free: 0
> 2021-11-08T06:36:01+01:00	[107367.710213][   T98]   cache: shmem_inode_cache, object size: 704, buffer size: 712, default order: 2, min order: 0
> 2021-11-08T06:36:01+01:00	[107367.710212][   T98] SLUB: Unable to allocate memory on node -1, gfp=0xcc0(GFP_KERNEL)
> 2021-11-08T06:36:01+01:00	[107367.710208][   T98]   node 0: slabs: 142, objs: 2924, free: 0
> 2021-11-08T06:36:01+01:00	[107367.710208][   T98]   cache: shmem_inode_cache, object size: 704, buffer size: 712, default order: 2, min order: 0
> 2021-11-08T06:36:01+01:00	[107367.710207][   T98] SLUB: Unable to allocate memory on node -1, gfp=0xcc0(GFP_KERNEL)
> 2021-11-08T06:36:01+01:00	[107367.710203][   T98]   node 0: slabs: 142, objs: 2924, free: 0
> 2021-11-08T06:36:01+01:00	[107367.710202][   T98]   cache: shmem_inode_cache, object size: 704, buffer size: 712, default order: 2, min order: 0
> 2021-11-08T06:36:01+01:00	[107367.710202][   T98] SLUB: Unable to allocate memory on node -1, gfp=0xcc0(GFP_KERNEL)
> 2021-11-08T06:36:01+01:00	[107367.710198][   T98]   node 0: slabs: 142, objs: 2924, free: 0
> 2021-11-08T06:36:01+01:00	[107367.710198][   T98]   cache: shmem_inode_cache, object size: 704, buffer size: 712, default order: 2, min order: 0
> 2021-11-08T06:36:01+01:00	[107367.710197][   T98] SLUB: Unable to allocate memory on node -1, gfp=0xcc0(GFP_KERNEL)
> 2021-11-08T06:36:01+01:00	[107367.710194][   T98]   node 0: slabs: 142, objs: 2924, free: 0
> 2021-11-08T06:36:01+01:00	[107367.710193][   T98]   cache: shmem_inode_cache, object size: 704, buffer size: 712, default order: 2, min order: 0
> 2021-11-08T06:36:01+01:00	[107367.710193][   T98] SLUB: Unable to allocate memory on node -1, gfp=0xcc0(GFP_KERNEL)
> 2021-11-08T06:36:01+01:00	[107367.710189][   T98]   node 0: slabs: 142, objs: 2924, free: 0
> 2021-11-08T06:36:01+01:00	[107367.710189][   T98]   cache: shmem_inode_cache, object size: 704, buffer size: 712, default order: 2, min order: 0
> 2021-11-08T06:36:01+01:00	[107367.710188][   T98] SLUB: Unable to allocate memory on node -1, gfp=0xcc0(GFP_KERNEL)
> 2021-11-08T06:36:01+01:00	[107367.710181][   T98]   node 0: slabs: 142, objs: 2924, free: 0
> 2021-11-08T06:36:01+01:00	[107367.710180][   T98]   cache: shmem_inode_cache, object size: 704, buffer size: 712, default order: 2, min order: 0
> 2021-11-08T06:36:01+01:00	[107367.710178][   T98] SLUB: Unable to allocate memory on node -1, gfp=0xcc0(GFP_KERNEL)
> 2021-11-08T06:36:01+01:00	[107367.329695][ T2572] 0 pages hwpoisoned
> 2021-11-08T06:36:01+01:00	[107367.329694][ T2572] 0 pages cma reserved
> 2021-11-08T06:36:01+01:00	[107367.329692][ T2572] 60098 pages reserved
> 2021-11-08T06:36:01+01:00	[107367.329691][ T2572] 0 pages HighMem/MovableOnly
> 2021-11-08T06:36:01+01:00	[107367.329690][ T2572] 2076206 pages RAM
> 2021-11-08T06:36:01+01:00	[107367.329688][ T2572] Total swap = 8388604kB
> 2021-11-08T06:36:01+01:00	[107367.329686][ T2572] Free swap  = 5261192kB
> 2021-11-08T06:36:01+01:00	[107367.329684][ T2572] Swap cache stats: add 967569, delete 898407, find 8158086/8171772
> 2021-11-08T06:36:01+01:00	[107367.329683][ T2572] 69189 pages in swap cache
> 2021-11-08T06:36:01+01:00	[107367.329678][ T2572] 181636 total pagecache pages
> 2021-11-08T06:36:01+01:00	[107367.329665][ T2572] Node 0 Normal: 0*4kB 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 0kB
> 2021-11-08T06:36:01+01:00	[107367.329654][ T2572] Node 0 DMA32: 0*4kB 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 0kB
> 2021-11-08T06:36:01+01:00	[107367.329648][ T2572] 0*4kB 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 0kB
> 2021-11-08T06:36:01+01:00	[107367.329645][   T98]   node 0: slabs: 138, objs: 2904, free: 0
> 2021-11-08T06:36:01+01:00	[107367.329644][   T98]   cache: shmem_inode_cache, object size: 704, buffer size: 712, default order: 2, min order: 0
> 2021-11-08T06:36:01+01:00	[107367.329643][   T98] SLUB: Unable to allocate memory on node -1, gfp=0xcc0(GFP_KERNEL)
> 2021-11-08T06:36:01+01:00	[107367.329640][ T2572] Node 0 DMA: 
> 2021-11-08T06:36:01+01:00	[107367.329639][ T2572] lowmem_reserve[]: 0 0 0 0 0
> 2021-11-08T06:36:01+01:00	[107367.329637][ T2572] Node 0 Normal free:0kB min:181292kB low:195236kB high:209180kB active_anon:4612596kB inactive_anon:1039828kB active_file:51220kB inactive_file:40680kB unevictable:132kB writepending:24kB present:6799360kB managed:6624588kB mlocked:0kB kernel_stack:4544kB pagetables:24120kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
> 2021-11-08T06:36:01+01:00	[107367.329636][ T2572]  6464
> 2021-11-08T06:36:01+01:00	[107367.329635][ T2572]  0 6464 6464
> 2021-11-08T06:36:01+01:00	[107367.329634][   T98]   node 0: slabs: 138, objs: 2904, free: 0
> 2021-11-08T06:36:01+01:00	[107367.329634][ T2572] lowmem_reserve[]: 0
> 2021-11-08T06:36:01+01:00	[107367.329633][   T98]   cache: shmem_inode_cache, object size: 704, buffer size: 712, default order: 2, min order: 0
> 2021-11-08T06:36:01+01:00	[107367.329632][   T98] SLUB: Unable to allocate memory on node -1, gfp=0xcc0(GFP_KERNEL)
> 2021-11-08T06:36:01+01:00	[107367.329630][ T2572] Node 0 DMA32 free:468kB min:15756kB low:18668kB high:21580kB active_anon:1386564kB inactive_anon:36792kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:1489480kB managed:1423944kB mlocked:0kB kernel_stack:0kB pagetables:4kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
> 2021-11-08T06:36:01+01:00	[107367.329629][ T2572] lowmem_reserve[]: 0 1351 7815 7815 7815
> 2021-11-08T06:36:01+01:00	[107367.329626][ T2572] Node 0 DMA free:16kB min:132kB low:164kB high:196kB active_anon:0kB inactive_anon:15840kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15984kB managed:15900kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
> 2021-11-08T06:36:01+01:00	[107367.329625][   T98]   node 0: slabs: 138, objs: 2904, free: 0
> 2021-11-08T06:36:01+01:00	[107367.329624][ T2572] Node 0 active_anon:5999160kB inactive_anon:1092956kB active_file:51220kB inactive_file:40680kB unevictable:132kB isolated(anon):0kB isolated(file):0kB mapped:53992kB dirty:24kB writeback:0kB shmem:357808kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 4689920kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
> 2021-11-08T06:36:01+01:00	[107367.329622][   T98]   cache: shmem_inode_cache, object size: 704, buffer size: 712, default order: 2, min order: 0
> 2021-11-08T06:36:01+01:00	[107367.329621][   T98] SLUB: Unable to allocate memory on node -1, gfp=0xcc0(GFP_KERNEL)
> 2021-11-08T06:36:01+01:00	[107367.329620][ T2572]  free:57 free_pcp:0 free_cma:0
> 2021-11-08T06:36:01+01:00	[107367.329620][ T2572]  mapped:13498 shmem:89452 pagetables:6031 bounce:0
> 2021-11-08T06:36:01+01:00	[107367.329620][ T2572]  slab_reclaimable:6786 slab_unreclaimable:13023
> 2021-11-08T06:36:01+01:00	[107367.329620][ T2572]  unevictable:33 dirty:6 writeback:0 unstable:0
> 2021-11-08T06:36:01+01:00	[107367.329620][ T2572]  active_file:12805 inactive_file:10170 isolated_file:0
> 2021-11-08T06:36:01+01:00	[107367.329620][ T2572] active_anon:1499790 inactive_anon:273239 isolated_anon:0
> 2021-11-08T06:36:01+01:00	[107367.329618][   T98] slab_out_of_memory: 33 callbacks suppressed
> 2021-11-08T06:36:01+01:00	[107367.329616][ T2572] Mem-Info:
> 2021-11-08T06:36:01+01:00	[107367.329615][ T2572] R13: 0000000040000000 R14: 00007f995469d5d0 R15: 00007f9971a6337c
> 2021-11-08T06:36:01+01:00	[107367.329615][ T2572] R10: 00007f9954a7c1a8 R11: 0000000000000293 R12: 0000000000001000
> 2021-11-08T06:36:01+01:00	[107367.329614][ T2572] RBP: 00007f99548133d0 R08: 0000000000000000 R09: 00007f9954813da0
> 2021-11-08T06:36:01+01:00	[107367.329614][ T2572] RDX: 0000000000001000 RSI: 00007f99548133d0 RDI: 000000000000002b
> 2021-11-08T06:36:01+01:00	[107367.329614][ T2572] RAX: ffffffffffffffda RBX: 000000000000002b RCX: 00007f998c7e23a7
> 2021-11-08T06:36:01+01:00	[107367.329613][ T2572] RSP: 002b:00007f994b7f0130 EFLAGS: 00000293 ORIG_RAX: 0000000000000001
> 2021-11-08T06:36:01+01:00	[107367.329612][ T2572] Code: 44 00 00 41 54 55 49 89 d4 53 48 89 f5 89 fb 48 83 ec 10 e8 5b fd ff ff 4c 89 e2 41 89 c0 48 89 ee 89 df b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 35 44 89 c7 48 89 44 24 08 e8 94 fd ff ff 48
> 2021-11-08T06:36:01+01:00	[107367.329611][ T2572] RIP: 0033:0x7f998c7e23a7
> 2021-11-08T06:36:01+01:00	[107367.329609][ T2572]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
> 2021-11-08T06:36:01+01:00	[107367.329607][ T2572]  do_syscall_64+0x52/0x1a0
> 2021-11-08T06:36:01+01:00	[107367.329605][ T2572]  ksys_write+0xa1/0xe0
> 2021-11-08T06:36:01+01:00	[107367.329604][ T2572]  vfs_write+0xad/0x1a0
> 2021-11-08T06:36:01+01:00	[107367.329603][ T2572]  new_sync_write+0x12d/0x1d0
> 2021-11-08T06:36:01+01:00	[107367.329601][ T2572]  ext4_file_write_iter+0xbe/0x370
> 2021-11-08T06:36:01+01:00	[107367.329600][ T2572]  ? generic_write_checks+0x64/0xc0
> 2021-11-08T06:36:01+01:00	[107367.329598][ T2572]  __generic_file_write_iter+0x192/0x1c0
> 2021-11-08T06:36:01+01:00	[107367.329597][ T2572]  generic_perform_write+0xb6/0x1b0
> 2021-11-08T06:36:01+01:00	[107367.329595][ T2572]  ext4_da_write_begin+0xcd/0x430
> 2021-11-08T06:36:01+01:00	[107367.329593][ T2572]  grab_cache_page_write_begin+0x1f/0x40
> 2021-11-08T06:36:01+01:00	[107367.329592][ T2572]  pagecache_get_page+0xb4/0x2d0
> 2021-11-08T06:36:01+01:00	[107367.329591][ T2572]  __alloc_pages_nodemask+0x2cf/0x320
> 2021-11-08T06:36:01+01:00	[107367.329590][ T2572]  __alloc_pages_slowpath+0x3ba/0xd40
> 2021-11-08T06:36:01+01:00	[107367.329589][ T2572]  try_to_free_pages+0xec/0x1d0
> 2021-11-08T06:36:01+01:00	[107367.329588][ T2572]  do_try_to_free_pages+0xc9/0x370
> 2021-11-08T06:36:01+01:00	[107367.329586][ T2572]  shrink_node+0xcc/0x420
> 2021-11-08T06:36:01+01:00	[107367.329585][ T2572]  shrink_slab+0x22f/0x2b0
> 2021-11-08T06:36:01+01:00	[107367.329584][ T2572]  do_shrink_slab+0x122/0x2c0
> 2021-11-08T06:36:01+01:00	[107367.329583][ T2572]  ttm_tt_shrinker_scan+0x40/0x70 [amdttm]
> 2021-11-08T06:36:01+01:00	[107367.329581][ T2572]  amdttm_bo_swapout+0x204/0x350 [amdttm]
> 2021-11-08T06:36:01+01:00	[107367.329578][ T2572]  ttm_tt_swapout+0x121/0x1c0 [amdttm]
> 2021-11-08T06:36:01+01:00	[107367.329574][ T2572]  ? set_page_dirty+0xe/0xb0
> 2021-11-08T06:36:01+01:00	[107367.329572][ T2572]  shmem_read_mapping_page_gfp+0x42/0x80
> 2021-11-08T06:36:01+01:00	[107367.329570][ T2572]  shmem_getpage_gfp+0x16f/0x8c0
> 2021-11-08T06:36:01+01:00	[107367.329569][ T2572]  shmem_alloc_and_acct_page+0x72/0x1b0
> 2021-11-08T06:36:01+01:00	[107367.329566][ T2572]  shmem_alloc_page+0x47/0x90
> 2021-11-08T06:36:01+01:00	[107367.329564][ T2572]  alloc_pages_vma+0x7c/0x210
> 2021-11-08T06:36:01+01:00	[107367.329562][ T2572]  __alloc_pages_nodemask+0x2cf/0x320
> 2021-11-08T06:36:01+01:00	[107367.329561][ T2572]  __alloc_pages_slowpath+0xd06/0xd40
> 2021-11-08T06:36:01+01:00	[107367.329560][ T2572]  ? wake_all_kswapds+0x54/0xb0
> 2021-11-08T06:36:01+01:00	[107367.329557][ T2572]  warn_alloc+0xfe/0x160
> 2021-11-08T06:36:01+01:00	[107367.329555][ T2572]  dump_stack+0x66/0x81
> 2021-11-08T06:36:01+01:00	[107367.329546][ T2572] Call Trace:
> 2021-11-08T06:36:01+01:00	[107367.329546][ T2572] Hardware name: Default string Default string/SKYBAY, BIOS 5.12 12/05/2017
> 2021-11-08T06:36:01+01:00	[107367.329545][ T2572] CPU: 0 PID: 2572 Comm: TBMiner Tainted: G           OE     5.4.0-hiveos #140.hiveos.210813
> 2021-11-08T06:36:01+01:00	[107367.329541][ T2572] TBMiner: page allocation failure: order:0, mode:0xc40(GFP_NOFS), nodemask=(null),cpuset=/,mems_allowed=0
> 2021-11-08T06:36:01+01:00	[107367.329539][ T2572] warn_alloc: 26 callbacks suppressed
> 

Noticed this since I have been trying miner (version 1.19 up to latest 1.23) and is still the case. Happy to share more details to fix this memory leak.

Thanks!

Erik

**Comment by sp-hash** [comment]
Do you get any error messages in the console?  like "cannot open shared object file" ?

then follow the install for linux

https://github.com/sp-hash/TeamBlackMiner/blob/main/INSTALL_LINUX.md

Can you try --no-stats does it help?

**Comment by esille** [comment]
> Do you get any error messages in the console? like "cannot open shared object file" ?
> 
yes, indeed
> then follow the install for linux
> 
> https://github.com/sp-hash/TeamBlackMiner/blob/main/INSTALL_LINUX.md
> 
I was hoping that once HiveOS introduced support for new miner it will sort out also dependencies, I was wrong. Anyway I copied manually missing libraries. Afterwards miner doesn't even start: with this error:

> modprobe: FATAL: Module fglrx not found in directory /lib/modules/5.4.0-hiveos

> Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly

tried to load module manually as root but it's not part of HiveOS distro.
> Can you try --no-stats does it help?
Will try and revert.  

Still I don't think memory usage should increase in any case. Can you introduce prerun checks to avoid it ?

**Comment by binaryf** [comment]
Memory leaks is not good. We were monitoring CPU usage and memory usage some time ago but not lately.
We will take a look at it.
About the ADL libs and dependencies, they are to old to use, and we want to replace them as fast as possible.

**Comment by esille** [comment]
> Memory leaks is not good. We were monitoring CPU usage and memory usage some time ago but not lately. We will take a look at it. About the ADL libs and dependencies, they are too old to use, and we want to replace them as fast as possible.

I have been monitoring and try to look more into memory leak issue and can confirm that even withn --no-stats memory leak is significant. On my rig with 8GB of RAM usually takes 7-8 hours to eat all available memory and miner crash. 

example htop after 7.5 hours of mining:

> [Wed Nov 10 10:19:07 2021] TBMiner: page allocation failure: order:0, mode:0xc40(GFP_NOFS), nodemask=(null),cpuset=/,mems_allowed=0
[Wed Nov 10 10:19:07 2021] CPU: 0 PID: 29678 Comm: TBMiner Tainted: G           OE     5.4.0-hiveos #140.hiveos.210813
[Wed Nov 10 10:19:07 2021] Hardware name: Default string Default string/SKYBAY, BIOS 5.12 12/05/2017


![Screen Shot 2021-11-10 at 10 19 12](https://user-images.githubusercontent.com/59832428/141086460-2831e853-70ce-403e-b83c-48507860b556.png)

**Comment by binaryf** [comment]
This is a serious bug. Top priority.

**Comment by esille** [comment]
> This is a serious bug. Top priority.

agree, let me know if you need more details to help with troubleshooting.

**Comment by sp-hash** [comment]
We have a found a fixed a problem with the DAG cache. Fixed in v1.24. This caused problems on nicehash because the dag epoc is switching frequently there.

**Comment by esille** [comment]
> We have a found a fixed a problem with the DAG cache. Fixed in v1.24. This caused problems on nicehash because the dag epoc is switching frequently there.

Thanks! Let me test and confirm.

**Comment by binaryf** [comment]
Yes. Please test v1.24 and see if the memleak is removed.

**Comment by esille** [comment]
> Yes. Please test v1.24 and see if the memleak is removed.

updated to 1.24 and unfortunately still same behavior. After 8.5 h miner uptime 81% of memory used and increasing.
![Screen Shot 2021-11-12 at 10 49 25](https://user-images.githubusercontent.com/59832428/141447039-e417a781-fa60-47f1-bd06-ecd38fa289c7.png)
![Screen Shot 2021-11-12 at 10 46 01](https://user-images.githubusercontent.com/59832428/141447095-391c7114-dc28-4353-8ff3-376c4a25e550.png)

**Comment by binaryf** [comment]
Reopened. Will go throuh every memory allocation again.

**Comment by binaryf** [comment]
The memory leak could be relative to hardware and setup.
Can you provide hardware information and used configuration.

**Comment by esille** [comment]
> The memory leak could be relative to hardware and setup. Can you provide hardware information and used configuration.

I don't believe so. I have been using HiveOS, usually updating to latest version on ONDA B250-D8P-D4 mining board, Intel Core i3-6100 CPU, 8GB RAM, 7 GPUs (1x 6800XT, 4x 5700 XT, 2x 5600XT). Only modification on top of default HiveOS is prometheus exporter and promtail to have history of events for anlysis. Been using TeamRedMiner and Phoenix Miner for months without any memory related issues. Actually, TeamRedMiner is rock stable for 3 days with less than 5% memory usage.

I can dump TBMiner during high memory usage for you to analyze. As there are multiple ways to get dumps could you please share what you prefer? And this will be big file for sure, could you please share where to upload?

**Comment by binaryf** [comment]
I think i will do a runtime analysis.

**Comment by esille** [comment]
> I think i will do a runtime analysis.

Ok, let me know in which version there will be changes and I can retest.

**Comment by sp-hash** [comment]
fixed in 1.26

**Comment by esille** [comment]
> fixed in 1.26

Tested it during weekend. Issue persists. Memory usage of miner increases and after about 8-9 hours on my rig (8GB RAM) got killed due to not enough memory. please reopen.

Thanks!

**Comment by sp-hash** [comment]
The fix in 1.26 was in ETH+ZIL mining mode. In v1.27 we fixed an important pool connect issue. Can you test please.

What cards are in your rig? AMD or NVIDIA? Do you have any unusual launch config?

**Comment by esille** [comment]
> The fix in 1.26 was in ETH+ZIL mining mode. In v1.27 we fixed an important pool connect issue. Can you test v1.27 please.
> 
> What cards are in your rig? AMD or NVIDIA? Do you have any unusual launch config?

Only AMD GPUs (1x 6800XT, 4x 5700 XT, 2x 5600XT). Running on HiveOS without any additional config. Let me test with 1.27 and revert.

**Comment by esille** [comment]
> > The fix in 1.26 was in ETH+ZIL mining mode. In v1.27 we fixed an important pool connect issue. Can you test v1.27 please.
> > What cards are in your rig? AMD or NVIDIA? Do you have any unusual launch config?
> 
> Only AMD GPUs (1x 6800XT, 4x 5700 XT, 2x 5600XT). Running on HiveOS without any additional config. Let me test with 1.27 and revert.
![Web capture_22-11-2021_154349_192 168 0 3](https://user-images.githubusercontent.com/59832428/142882632-c7c94d4d-bbe4-474f-8e7f-9a5bcf1cb81f.jpeg)
![Web capture_22-11-2021_154536_192 168 0 3](https://user-images.githubusercontent.com/59832428/142882644-8e75a672-d44d-4a7f-9511-7716c1e0bc8c.jpeg)


Issue persists. This time I have put together all logs and I can confirm it's 99% issue during Dag generation. Have a look into attached screencaps from grafana using node_exporter and Loki (miner log) as datasource. Each time Dag generation start memory is allocated but not freed up afterwards.

**Comment by sp-hash** [comment]
v1.28 the cl dag code is rewritten and a cache is added to improve performance on ETC+ZIL

**Comment by esille** [comment]
> v1.28 the cl dag code is rewritten and a cache is added to improve performance on ETC+ZIL

ok let's see. Any ETA for release date?

**Comment by sp-hash** [comment]
friday or sunday

**Comment by sp-hash** [comment]
fixed in v1.28

**Comment by esille** [comment]
couldn't confirm as 1.28 doesn't work at all due to issue #161

**Comment by esille** [comment]
> fixed in v1.28

Might be fixed already in 1.28 but that version doesn't work at all on my rig with RX6800XT. 6hours mining with 1.29 and so far memory usage is lower and not increasing during every DAG generation.

**Comment by esille** [comment]
memory leak is gone in v 1.29. Thanks
