### ISSUE TITLE
v2.11 (Windows): eth+ethb3 ethash never starts mining (RX5700)

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#420]
`TeamBlackMiner-v2.11\TBMiner.exe --algo eth+ethb3 --hostname europe.ethash-hub.miningpoolhub.com --wallet *********************.****************--port 20605 --server-passwd x --ethb3-hostname ethashb3.eu.mine.zergpool.com --ethb3-wallet ******************* --ethb3-passwd c=BTC,ID=***************** --ethb3-port 9996 --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

Ethash never start mining:

```
00:00:00 [2023-12-03 16:11:47.308]
00:00:00 [2023-12-03 16:11:47.402] OpenCL driver version: 546.1
00:00:00 [2023-12-03 16:11:47.433] Cuda driver version: 12.3
00:00:00 [2023-12-03 16:11:47.433] Cuda runtime API version: 12.0
00:00:00 [2023-12-03 16:11:47.433]
00:00:00 [2023-12-03 16:11:47.433]
00:00:00 [2023-12-03 16:11:47.433]
00:00:00 [2023-12-03 16:11:47.433] Welcome to Team Black Miner 2.11
00:00:00 [2023-12-03 16:11:47.433]
00:00:00 [2023-12-03 16:11:47.433]
00:00:00 [2023-12-03 16:11:47.433] GPU0 gfx1010:xnack- 8GB added to miner as OpenCL device
00:00:00 [2023-12-03 16:11:47.433] Trying europe.ethash-hub.miningpoolhub.com:20605 (ethash)
00:00:00 [2023-12-03 16:11:47.433] Trying ethashb3.eu.mine.zergpool.com:9996 (ethashb3)
00:00:00 [2023-12-03 16:11:47.433] Api server started at 127.0.0.1:4001
00:00:00 [2023-12-03 16:11:47.433] GPU0 Started CL work thread
00:00:00 [2023-12-03 16:11:47.433] GPU0 Started CL work thread
00:00:00 [2023-12-03 16:11:47.622] ethashb3.eu.mine.zergpool.com: Pool responded successfully to subscribe
00:00:00 [2023-12-03 16:11:47.701] europe.ethash-hub.miningpoolhub.com: Pool responded successfully to subscribe
00:00:00 [2023-12-03 16:11:47.716] ethashb3.eu.mine.zergpool.com: Pool responded successfully to extranonce subscribe
00:00:00 [2023-12-03 16:11:47.732] ethashb3.eu.mine.zergpool.com: Extranonce is set to 2ded000000000000
00:00:00 [2023-12-03 16:11:47.779] ethashb3.eu.mine.zergpool.com: Pool responded successfully to authorize
00:00:00 [2023-12-03 16:11:47.798] ethashb3.eu.mine.zergpool.com: Difficulty is set to 0.249996
00:00:00 [2023-12-03 16:11:47.811] europe.ethash-hub.miningpoolhub.com: Difficulty is set to 3.000000
00:00:00 [2023-12-03 16:11:47.826] GPU0 Starting generating ethashb3 dag (Epoch: 41)
00:00:00 [2023-12-03 16:11:47.842] GPU0 Starting generating ethash dag (Epoch: 213)
00:00:00 [2023-12-03 16:11:47.905] europe.ethash-hub.miningpoolhub.com: Pool responded successfully to authorize
00:00:00 [2023-12-03 16:11:52.703] GPU0 DAG generated in 4.88 seconds (1384446kb)
00:00:00 [2023-12-03 16:11:52.703] GPU0 XIntensity set to Dynamic
00:00:00 [2023-12-03 16:11:52.715] GPU0 Fetching ethashb3 dag (Epoch: 41)
00:00:00 [2023-12-03 16:11:52.715] GPU0 XIntensity set to Dynamic
00:00:00 [2023-12-03 16:11:53.144] GPU0 Dag buffer verified ok!
00:00:01 [2023-12-03 16:12:47.033] miningpoolhub.com (ethash)    PING: 125ms    DIFFICULTY: 3.00     EPOCH: 213
00:00:01 [2023-12-03 16:12:47.033]
00:00:01 [2023-12-03 16:12:47.033] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:01 [2023-12-03 16:12:47.033] GPU0    5700XT   OpenCL  0       0       0/0     46      2040    1840    0
00:00:01 [2023-12-03 16:12:47.033]                                                                          0
00:00:01 [2023-12-03 16:12:47.033] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:01 [2023-12-03 16:12:47.033] GPU0    5700XT   0.00 H/W      0.00 H/s      0.00 H/s      0/0/0        100.00%
00:00:01 [2023-12-03 16:12:47.033]                  0.00 H/W      0.00 H/s      0.00 H/s      0/0/0        100.00%
00:00:01 [2023-12-03 16:12:47.033]
00:00:01 [2023-12-03 16:12:47.033] SHARES PER MINUTE: 0.00                              POOL HASHRATE: 0.00 H/s
00:00:01 [2023-12-03 16:12:47.033]
00:00:01 [2023-12-03 16:12:47.033] eu.mine.zergpool.com (ethashb3)    PING: 47ms    DIFFICULTY: 0.250    EPOCH: 41
00:00:01 [2023-12-03 16:12:47.033]
00:00:01 [2023-12-03 16:12:47.033] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:01 [2023-12-03 16:12:47.033] GPU0    5700XT   OpenCL  -1      0       0/0     46      2040    1840    0
00:00:01 [2023-12-03 16:12:47.033]                                                                          0
00:00:01 [2023-12-03 16:12:47.033] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:01 [2023-12-03 16:12:47.033] GPU0    5700XT   0.00 H/W      56.51 MH/s    55.75 MH/s    0/0/0        100.00%
00:00:01 [2023-12-03 16:12:47.033]                  0.00 H/W      56.51 MH/s    55.75 MH/s    0/0/0        100.00%
00:00:01 [2023-12-03 16:12:47.033]
00:00:01 [2023-12-03 16:12:47.033] SHARES PER MINUTE: 0.00                              POOL HASHRATE: 0.00 H/s
00:00:01 [2023-12-03 16:12:47.033]
00:00:02 [2023-12-03 16:13:47.040] miningpoolhub.com (ethash)    PING: 131ms    DIFFICULTY: 3.00     EPOCH: 213
00:00:02 [2023-12-03 16:13:47.040]
00:00:02 [2023-12-03 16:13:47.040] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:02 [2023-12-03 16:13:47.040] GPU0    5700XT   OpenCL  0       0       0/0     46      2040    1840    0
00:00:02 [2023-12-03 16:13:47.040]                                                                          0
00:00:02 [2023-12-03 16:13:47.040] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:02 [2023-12-03 16:13:47.040] GPU0    5700XT   0.00 H/W      0.00 H/s      0.00 H/s      0/0/0        100.00%
00:00:02 [2023-12-03 16:13:47.040]                  0.00 H/W      0.00 H/s      0.00 H/s      0/0/0        100.00%
00:00:02 [2023-12-03 16:13:47.040]
00:00:02 [2023-12-03 16:13:47.040] SHARES PER MINUTE: 0.00                              POOL HASHRATE: 0.00 H/s
00:00:02 [2023-12-03 16:13:47.040]
00:00:02 [2023-12-03 16:13:47.040] eu.mine.zergpool.com (ethashb3)    PING: 68ms    DIFFICULTY: 0.250    EPOCH: 41
00:00:02 [2023-12-03 16:13:47.040]
00:00:02 [2023-12-03 16:13:47.040] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:02 [2023-12-03 16:13:47.040] GPU0    5700XT   OpenCL  -1      0       0/0     46      2040    1840    0
00:00:02 [2023-12-03 16:13:47.040]                                                                          0
00:00:02 [2023-12-03 16:13:47.040] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:02 [2023-12-03 16:13:47.040] GPU0    5700XT   0.00 H/W      56.51 MH/s    55.75 MH/s    0/0/0        100.00%
00:00:02 [2023-12-03 16:13:47.040]                  0.00 H/W      56.51 MH/s    55.75 MH/s    0/0/0        100.00%
00:00:02 [2023-12-03 16:13:47.040]
00:00:02 [2023-12-03 16:13:47.040] SHARES PER MINUTE: 0.00                              POOL HASHRATE: 0.00 H/s
```

**Comment by sp-hash** [comment]
fixed in v2.12

**Comment by UselessGuru** [comment]
> should work in v2.13

Nope. Still not fixed (with new 2.13). It is annoying to report same issue again and again. Can't you test yourself?

**Comment by sp-hash** [comment]
Your bat is missing a space after workername and --port  (****************--port 20605 )
